In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from Utils import utils

In [5]:
%matplotlib inline

# Lendo a última base de dados

In [6]:
Extract = utils()      
dataframe = Extract.GetLastPickle()
dataframe.head(5)

0         1         2         3         4         5         6  \
0  0.004348  0.004743  0.004743  0.004743  0.004743  0.004743  0.004743   
1  0.004743  0.004743  0.004743  0.004743  0.005138  0.005138  0.005138   
2  0.004348  0.004348  0.004743  0.004743  0.004743  0.005138  0.004743   
3  0.004743  0.005138  0.005138  0.005138  0.005138  0.004743  0.004743   
4  0.004743  0.004743  0.004743  0.005138  0.005138  0.005138  0.004743   

          7         8         9    ...         2022      2023      2024  \
0  0.004743  0.004743  0.004743    ...     0.005138  0.005138  0.005138   
1  0.004743  0.004743  0.004743    ...     0.005138  0.005138  0.005138   
2  0.004743  0.004743  0.004743    ...     0.004743  0.004743  0.004743   
3  0.004743  0.004743  0.005138    ...     0.004743  0.004743  0.004743   
4  0.004743  0.004348  0.004348    ...     0.004348  0.004348  0.004348   

       2025      2026      2027      2028      2029      2030     Label  
0  0.004743  0.004743  0.005138  0.005138  0.005138  0.004743  oxigenio  
1  0.005138  0.004743  0.004743  0.004743  0.005138  0.005138  oxigenio  
2  0.004743  0.004743  0.004743  0.004348  0.004743  0.004743  oxigenio  
3  0.004743  0.004743  0.004743  0.004743  0.004743  0.004743  oxigenio  
4  0.004743  0.004743  0.004743  0.004743  0.004743  0.004348  oxigenio  

[5 rows x 2032 columns]

# Separando dados

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [20]:
data = dataframe.loc[:, dataframe.columns != 'Label']
target =  dataframe['Label']
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.30, random_state=101)

# Treinamento do SVC

In [21]:
from sklearn.svm import SVC

In [22]:
model = SVC()

In [23]:
model.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

# Predição e validação

In [24]:
predictions = model.predict(X_test)

In [25]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,predictions))

[[   0  688    0    0    0    0]
 [   0 2638    0    0    0    0]
 [   0  393    0    0    0    0]
 [   0   13    0    0    0    0]
 [   0  278    0    0    0    0]
 [   0  416    0    0    0    0]]


In [26]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

    carbono       0.00      0.00      0.00       688
      cloro       0.60      1.00      0.75      2638
      cobre       0.00      0.00      0.00       393
      ferro       0.00      0.00      0.00        13
   oxigenio       0.00      0.00      0.00       278
    silicio       0.00      0.00      0.00       416

avg / total       0.36      0.60      0.45      4426



C:\Users\Jarvis\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


# Procura na grade

Vamos buscar os melhores parametros

In [27]:
param_grid = {'C': [0.1,1, 10, 100, 1000], 'gamma': [1,0.1,0.01,0.001,0.0001], 'kernel': ['rbf']} 

In [28]:
from sklearn.model_selection import GridSearchCV

In [29]:
grid = GridSearchCV(SVC(),param_grid,refit=True,verbose=3)

In [30]:
grid.fit(X_train,y_train)

Fitting 3 folds for each of 25 candidates, totalling 75 fits
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] ....... C=0.1, gamma=1, kernel=rbf, score=0.585656, total= 2.8min
[CV] C=0.1, gamma=1, kernel=rbf ......................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  4.5min remaining:    0.0s


[CV] ....... C=0.1, gamma=1, kernel=rbf, score=0.585656, total= 2.8min
[CV] C=0.1, gamma=1, kernel=rbf ......................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:  8.9min remaining:    0.0s


[CV] ....... C=0.1, gamma=1, kernel=rbf, score=0.586217, total= 2.7min
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ..... C=0.1, gamma=0.1, kernel=rbf, score=0.585656, total= 3.0min
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ..... C=0.1, gamma=0.1, kernel=rbf, score=0.585656, total= 3.1min
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ..... C=0.1, gamma=0.1, kernel=rbf, score=0.586217, total= 3.1min
[CV] C=0.1, gamma=0.01, kernel=rbf ...................................
[CV] .... C=0.1, gamma=0.01, kernel=rbf, score=0.585656, total= 3.0min
[CV] C=0.1, gamma=0.01, kernel=rbf ...................................
[CV] .... C=0.1, gamma=0.01, kernel=rbf, score=0.585656, total= 2.9min
[CV] C=0.1, gamma=0.01, kernel=rbf ...................................
[CV] .... C=0.1, gamma=0.01, kernel=rbf, score=0.586217, total= 2.7min
[CV] C=0.1, gamma=0.001, kernel=rbf ..................................
[CV] .

[Parallel(n_jobs=1)]: Done  75 out of  75 | elapsed: 301.2min finished


GridSearchCV(cv=None, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'C': [0.1, 1, 10, 100, 1000], 'gamma': [1, 0.1, 0.01, 0.001, 0.0001], 'kernel': ['rbf']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring=None, verbose=3)

In [31]:
grid.best_params_

{'C': 1000, 'gamma': 1, 'kernel': 'rbf'}

In [32]:
grid_predictions = grid.predict(X_test)

In [33]:
print(confusion_matrix(y_test,grid_predictions))

[[ 677    1    0    0   10    0]
 [  31 2532    0    0    6   69]
 [   1   37  352    0    1    2]
 [   0    0    0    7    5    1]
 [  16    9    0    0  253    0]
 [   3   52    0    0    0  361]]


In [34]:
print(classification_report(y_test,grid_predictions))

             precision    recall  f1-score   support

    carbono       0.93      0.98      0.96       688
      cloro       0.96      0.96      0.96      2638
      cobre       1.00      0.90      0.94       393
      ferro       1.00      0.54      0.70        13
   oxigenio       0.92      0.91      0.92       278
    silicio       0.83      0.87      0.85       416

avg / total       0.95      0.94      0.94      4426

